name: "Build & Release"

on:
  push:
    paths:
      - pubspec.yaml

jobs:
  pre-build-checks:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.check-version.outputs.version_changed }}
      version: ${{ steps.extract-version.outputs.version }}
      tag_exists: ${{ steps.check-tag.outputs.tag_exists }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Fetch the last two commits for comparison

      - name: Check if version changed
        id: check-version
        run: |
          VERSION_CHANGED=$(git diff HEAD^ HEAD -- pubspec.yaml | grep 'version:')
          if [[ -z "$VERSION_CHANGED" ]]; then
            echo "Version change not detected."
            echo "::set-output name=version_changed::false"
          else
            echo "Version change detected."
            echo "::set-output name=version_changed::true"
          fi

      - name: Extract version from pubspec.yaml
        id: extract-version
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "::set-output name=version::$version"

      - name: Check if Tag Exists
        id: check-tag
        run: |
          version=${{ steps.extract-version.outputs.version }}
          if git rev-parse "v$version" >/dev/null 2>&1; then
            echo "Tag v$version already exists."
            echo "::set-output name=tag_exists::true"
          else
            echo "Tag v$version does not exist."
            echo "::set-output name=tag_exists::false"
          fi

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.9

  build:
    needs: pre-build-checks
    if: needs.check-version.outputs.version_changed == 'true' && needs.check-version.outputs.tag_exists == 'false'
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: "stable"
      - name: Install Dependencies
        run: flutter pub get

      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json
      
      - name: Create firebase_options.dart
        run: |
          echo "${{ secrets.FIREBASE_OPTIONS_DART }}" > lib/firebase_options.dart

      - name: Create .env
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v${{ needs.check-version.outputs.version }}
          token: ${{ secrets.TOKEN }}
